/**
 * @file sprites.h
 * @brief Includes all LVGL sprite headers generated by this script run.
 */

#ifndef LVGL_SPRITES_H
#define LVGL_SPRITES_H

#ifdef __cplusplus
extern "C" {
#endif

// Include all sprite headers
#include "3buttondungeon/sprite_3buttondungeon.h"
#include "sprite_Normal_Walking_02.h"

// Array of all generated sprites
extern const lv_img_dsc_t* all_generated_sprites[];
extern const uint8_t all_generated_sprites_count;

#ifdef __cplusplus
}
#endif

#endif /* LVGL_SPRITES_H */
